/* https://tesseract-ocr.github.io/tessdoc/Data-Files#data-files-for-version-400-november-29-2016 */
const languages = [
  { code: "eng", lang: "English" },
  { code: "afr", lang: "Afrikaans" },
  { code: "sqi", lang: "Albanian" },
  { code: "amh", lang: "Amharic" },
  { code: "ara", lang: "Arabic" },
  { code: "asm", lang: "Assamese" },
  { code: "aze", lang: "Azerbaijani" },
  { code: "bel", lang: "Belarusian" },
  { code: "ben", lang: "Bengali" },
  { code: "bod", lang: "Tibetan" },
  { code: "bos", lang: "Bosnian" },
  { code: "bul", lang: "Bulgarian" },
  { code: "ceb", lang: "Cebuano" },
  { code: "ces", lang: "Czech" },
  { code: "chi_sim", lang: "Chinese (Simplified)" },
  { code: "chi_tra", lang: "Chinese (Traditional)" },
  { code: "chr", lang: "Cherokee" },
  { code: "cym", lang: "Welsh" },
  { code: "dan", lang: "Danish" },
  { code: "deu", lang: "German" },
  { code: "dzo", lang: "Dzongkha" },
  { code: "epo", lang: "Esperanto" },
  { code: "est", lang: "Estonian" },
  { code: "eus", lang: "Basque" },
  { code: "fas", lang: "Persian" },
  { code: "fin", lang: "Finnish" },
  { code: "fra", lang: "French" },
  { code: "gle", lang: "Irish" },
  { code: "glg", lang: "Galician" },
  { code: "guj", lang: "Gujarati" },
  { code: "hin", lang: "Hindi" },
  { code: "hrv", lang: "Croatian" },
  { code: "hun", lang: "Hungarian" },
  { code: "ind", lang: "Indonesian" },
  { code: "isl", lang: "Icelandic" },
  { code: "ita", lang: "Italian" },
  { code: "jpn", lang: "Japanese" },
  { code: "kat", lang: "Georgian" },
  { code: "kaz", lang: "Kazakh" },
  { code: "kir", lang: "Kirghiz; Kyrgyz" },
  { code: "lat", lang: "Latin" },
  { code: "lav", lang: "Latvian" },
  { code: "lit", lang: "Lithuanian" },
  { code: "mlt", lang: "Maltese" },
  { code: "msa", lang: "Malay" },
  { code: "nep", lang: "Nepali" },
  { code: "nld", lang: "Dutch; Flemish" },
  { code: "nor", lang: "Norwegian" },
  { code: "pol", lang: "Polish" },
  { code: "por", lang: "Portuguese" },
  { code: "ron", lang: "Romanian" },
  { code: "rus", lang: "Russian" },
  { code: "san", lang: "Sanskrit" },
  { code: "slk", lang: "Slovak" },
  { code: "slv", lang: "Slovenian" },
  { code: "spa", lang: "Spanish" },
  { code: "srp", lang: "Serbian" },
  { code: "swe", lang: "Swedish" },
  { code: "syr", lang: "Syriac" },
  { code: "tgk", lang: "Tajik" },
  { code: "tha", lang: "Thai" },
  { code: "tur", lang: "Turkish" },
  { code: "ukr", lang: "Ukrainian" },
  { code: "uzb", lang: "Uzbek" },
  { code: "vie", lang: "Vietnamese" },
  { code: "yid", lang: "Yiddish" },
];

export default languages;
